# Rename this file to languages.toml to enable multilingual support
[ja]
languageName = "æ—¥æœ¬èª"
languagedirection = "ltr"
title = "TakoyakiSoft"
weight = 1

[ja.params.dateFormat]
published = "2006å¹´01æœˆ02æ—¥"
lastUpdated = "2006å¹´01æœˆ02æ—¥ 15:04"

[ja.params.sidebar]
emoji = "ğŸ•¹ï¸"
subtitle = "æ§˜ã€…ãªã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢ã®ä½¿ã„æ–¹ã‚’åˆ†ã‹ã‚Šã‚„ã™ãè§£èª¬ã—ã¾ã™ã€‚"


[en]
languageName = "English"
languagedirection = "ltr"
title = "TakoyakiSoft"
weight = 1

[en.params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04"

[en.params.sidebar]
emoji = "ğŸ•¹ï¸"
subtitle = "Explaining how to use various software in an easy-to-understand manner."

[zh-cn]
languageName = "ç®€ä½“ä¸­æ–‡"
languagedirection = "ltr"
title = "TakoyakiSoft"
weight = 1

[zh-cn.params.dateFormat]
published = "2006å¹´01æœˆ02æ—¥"
lastUpdated = "2006å¹´01æœˆ02æ—¥ 15:04"

[zh-cn.params.sidebar]
emoji = "ğŸ•¹ï¸"
subtitle = "ä»¥é€šä¿—æ˜“æ‡‚çš„æ–¹å¼è®²è§£å„ç§è½¯ä»¶çš„ä½¿ç”¨æ–¹æ³•ã€‚"
